export const states = [
    {
      id: 1,
      name: "Andhra Pradesh",
      capital: "Amaravati",
      population: 49577103,
      country: "India",
    },
    {
      id: 2,
      name: "Arunachal Pradesh",
      capital: "Itanagar",
      population: 1383727,
      country: "India",
    },
    {
      id: 3,
      name: "Assam",
      capital: "Dispur",
      population: 31205576,
      country: "India",
    },
    {
      id: 4,
      name: "Bihar",
      capital: "Patna",
      population: 104099452,
      country: "India",
    },
    {
      id: 5,
      name: "Chhattisgarh",
      capital: "Raipur",
      population: 25545198,
      country: "India",
    },
    {
      id: 6,
      name: "Goa",
      capital: "Panaji",
      population: 1458545,
      country: "India",
    },
    {
      id: 7,
      name: "Gujarat",
      capital: "Gandhinagar",
      population: 60439692,
      country: "India",
    },
    {
      id: 8,
      name: "Haryana",
      capital: "Chandigarh",
      population: 25351462,
      country: "India",
    },
    {
      id: 9,
      name: "Himachal Pradesh",
      capital: "Shimla",
      population: 6864602,
      country: "India",
    },
    {
      id: 10,
      name: "Jharkhand",
      capital: "Ranchi",
      population: 32988134,
      country: "India",
    },
    {
      id: 11,
      name: "Karnataka",
      capital: "Bengaluru",
      population: 61095297,
      country: "India",
    },
    {
      id: 12,
      name: "Kerala",
      capital: "Thiruvananthapuram",
      population: 33406061,
      country: "India",
    },
    {
      id: 13,
      name: "Madhya Pradesh",
      capital: "Bhopal",
      population: 72626809,
      country: "India",
    },
    {
      id: 14,
      name: "Maharashtra",
      capital: "Mumbai",
      population: 112374333,
      country: "India",
    },
    {
      id: 15,
      name: "Manipur",
      capital: "Imphal",
      population: 2855794,
      country: "India",
    },
    {
      id: 16,
      name: "Meghalaya",
      capital: "Shillong",
      population: 2966889,
      country: "India",
    },
    {
      id: 17,
      name: "Mizoram",
      capital: "Aizawl",
      population: 1097206,
      country: "India",
    },
    {
      id: 18,
      name: "Nagaland",
      capital: "Kohima",
      population: 1978502,
      country: "India",
    },
    {
      id: 19,
      name: "Odisha",
      capital: "Bhubaneswar",
      population: 41974218,
      country: "India",
    },
    {
      id: 20,
      name: "Punjab",
      capital: "Chandigarh",
      population: 27743338,
      country: "India",
    },
    {
      id: 21,
      name: "Rajasthan",
      capital: "Jaipur",
      population: 68548437,
      country: "India",
    },
    {
      id: 22,
      name: "Sikkim",
      capital: "Gangtok",
      population: 610577,
      country: "India",
    },
    {
      id: 23,
      name: "Tamil Nadu",
      capital: "Chennai",
      population: 72147030,
      country: "India",
    },
    {
      id: 24,
      name: "Telangana",
      capital: "Hyderabad",
      population: 35193978,
      country: "India",
    },
    {
      id: 25,
      name: "Tripura",
      capital: "Agartala",
      population: 3673917,
      country: "India",
    },
    {
      id: 26,
      name: "Uttar Pradesh",
      capital: "Lucknow",
      population: 199812341,
      country: "India",
    },
    {
      id: 27,
      name: "Uttarakhand",
      capital: "Dehradun",
      population: 10086292,
      country: "India",
    },
    {
      id: 28,
      name: "West Bengal",
      capital: "Kolkata",
      population: 91276115,
      country: "India",
    },
    {
      id: 29,
      name: "Alabama",
      capital: "Montgomery",
      population: 5024279,
      country: "USA",
    },
    {
      id: 30,
      name: "Alaska",
      capital: "Juneau",
      population: 733391,
      country: "USA",
    },
    {
      id: 31,
      name: "Arizona",
      capital: "Phoenix",
      population: 7151502,
      country: "USA",
    },
    {
      id: 32,
      name: "Arkansas",
      capital: "Little Rock",
      population: 3011524,
      country: "USA",
    },
    {
      id: 33,
      name: "California",
      capital: "Sacramento",
      population: 39538223,
      country: "USA",
    },
    {
      id: 34,
      name: "Colorado",
      capital: "Denver",
      population: 5773714,
      country: "USA",
    },
    {
      id: 35,
      name: "Connecticut",
      capital: "Hartford",
      population: 3605944,
      country: "USA",
    },
    {
      id: 36,
      name: "Delaware",
      capital: "Dover",
      population: 989948,
      country: "USA",
    },
    {
      id: 37,
      name: "Florida",
      capital: "Tallahassee",
      population: 21538187,
      country: "USA",
    },
    {
      id: 38,
      name: "Georgia",
      capital: "Atlanta",
      population: 10711908,
      country: "USA",
    },
    {
      id: 39,
      name: "Hawaii",
      capital: "Honolulu",
      population: 1455271,
      country: "USA",
    },
    {
      id: 40,
      name: "Idaho",
      capital: "Boise",
      population: 1891506,
      country: "USA",
    },
    {
      id: 41,
      name: "Illinois",
      capital: "Springfield",
      population: 12812508,
      country: "USA",
    },
    {
      id: 42,
      name: "Indiana",
      capital: "Indianapolis",
      population: 6785528,
      country: "USA",
    },
    {
      id: 43,
      name: "Iowa",
      capital: "Des Moines",
      population: 3190369,
      country: "USA",
    },
    {
      id: 44,
      name: "Kansas",
      capital: "Topeka",
      population: 2913314,
      country: "USA",
    },
    {
      id: 45,
      name: "Kentucky",
      capital: "Frankfort",
      population: 4505836,
      country: "USA",
    },
    {
      id: 46,
      name: "Louisiana",
      capital: "Baton Rouge",
      population: 4657757,
      country: "USA",
    },
    {
      id: 47,
      name: "Maine",
      capital: "Augusta",
      population: 1369219,
      country: "USA",
    },
    {
      id: 48,
      name: "Maryland",
      capital: "Annapolis",
      population: 6177224,
      country: "USA",
    },
    {
      id: 49,
      name: "Massachusetts",
      capital: "Boston",
      population: 7029917,
      country: "USA",
    },
    {
      id: 50,
      name: "Michigan",
      capital: "Lansing",
      population: 10077331,
      country: "USA",
    },
    {
      id: 51,
      name: "Minnesota",
      capital: "Saint Paul",
      population: 5706494,
      country: "USA",
    },
    {
      id: 52,
      name: "Mississippi",
      capital: "Jackson",
      population: 2961279,
      country: "USA",
    },
    {
      id: 53,
      name: "Missouri",
      capital: "Jefferson City",
      population: 6154913,
      country: "USA",
    },
    {
      id: 54,
      name: "Montana",
      capital: "Helena",
      population: 1084225,
      country: "USA",
    },
    {
      id: 55,
      name: "Nebraska",
      capital: "Lincoln",
      population: 1961504,
      country: "USA",
    },
    {
      id: 56,
      name: "Nevada",
      capital: "Carson City",
      population: 3104614,
      country: "USA",
    },
    {
      id: 57,
      name: "New Hampshire",
      capital: "Concord",
      population: 1377529,
      country: "USA",
    },
    {
      id: 58,
      name: "New Jersey",
      capital: "Trenton",
      population: 9288994,
      country: "USA",
    },
    {
      id: 59,
      name: "New Mexico",
      capital: "Santa Fe",
      population: 2117522,
      country: "USA",
    },
    {
      id: 60,
      name: "New York",
      capital: "Albany",
      population: 20201249,
      country: "USA",
    },
    {
      id: 61,
      name: "North Carolina",
      capital: "Raleigh",
      population: 10439388,
      country: "USA",
    },
    {
      id: 62,
      name: "North Dakota",
      capital: "Bismarck",
      population: 779094,
      country: "USA",
    },
    {
      id: 63,
      name: "Ohio",
      capital: "Columbus",
      population: 11799448,
      country: "USA",
    },
    {
      id: 64,
      name: "Oklahoma",
      capital: "Oklahoma City",
      population: 3963516,
      country: "USA",
    },
    {
      id: 65,
      name: "Oregon",
      capital: "Salem",
      population: 4237256,
      country: "USA",
    },
    {
      id: 66,
      name: "Pennsylvania",
      capital: "Harrisburg",
      population: 13002700,
      country: "USA",
    },
    {
      id: 67,
      name: "Rhode Island",
      capital: "Providence",
      population: 1097379,
      country: "USA",
    },
    {
      id: 68,
      name: "South Carolina",
      capital: "Columbia",
      population: 5118425,
      country: "USA",
    },
    {
      id: 69,
      name: "South Dakota",
      capital: "Pierre",
      population: 886667,
      country: "USA",
    },
    {
      id: 70,
      name: "Tennessee",
      capital: "Nashville",
      population: 6897576,
      country: "USA",
    },
    {
      id: 71,
      name: "Texas",
      capital: "Austin",
      population: 29145505,
      country: "USA",
    },
    {
      id: 72,
      name: "Utah",
      capital: "Salt Lake City",
      population: 3271616,
      country: "USA",
    },
    {
      id: 73,
      name: "Vermont",
      capital: "Montpelier",
      population: 643077,
      country: "USA",
    },
    {
      id: 74,
      name: "Virginia",
      capital: "Richmond",
      population: 8631393,
      country: "USA",
    },
    {
      id: 75,
      name: "Washington",
      capital: "Olympia",
      population: 7693612,
      country: "USA",
    },
    {
      id: 76,
      name: "West Virginia",
      capital: "Charleston",
      population: 1793716,
      country: "USA",
    },
    {
      id: 77,
      name: "Wisconsin",
      capital: "Madison",
      population: 5893718,
      country: "USA",
    },
    {
      id: 78,
      name: "Wyoming",
      capital: "Cheyenne",
      population: 576851,
      country: "USA",
    },
    {
      id: 1,
      name: "Adygea",
      population: 450000,
      country: "Russia",
      capital: "Maykop",
    },
    {
      id: 2,
      name: "Altai Krai",
      population: 2300000,
      country: "Russia",
      capital: "Barnaul",
    },
    {
      id: 3,
      name: "Altai Republic",
      population: 200000,
      country: "Russia",
      capital: "Gorno-Altaysk",
    },
    {
      id: 4,
      name: "Amur Oblast",
      population: 800000,
      country: "Russia",
      capital: "Blagoveshchensk",
    },
    {
      id: 5,
      name: "Arkhangelsk Oblast",
      population: 1100000,
      country: "Russia",
      capital: "Arkhangelsk",
    },
    {
      id: 6,
      name: "Astrakhan Oblast",
      population: 1000000,
      country: "Russia",
      capital: "Astrakhan",
    },
    {
      id: 7,
      name: "Bashkortostan",
      population: 4000000,
      country: "Russia",
      capital: "Ufa",
    },
    {
      id: 8,
      name: "Buryatia",
      population: 1000000,
      country: "Russia",
      capital: "Ulan-Ude",
    },
    {
      id: 9,
      name: "Chechen Republic",
      population: 1500000,
      country: "Russia",
      capital: "Grozny",
    },
    {
      id: 10,
      name: "Chelyabinsk Oblast",
      population: 3600000,
      country: "Russia",
      capital: "Chelyabinsk",
    },
    {
      id: 11,
      name: "Chukotka Autonomous Okrug",
      population: 50000,
      country: "Russia",
      capital: "Anadyr",
    },
    {
      id: 12,
      name: "Chuvash Republic",
      population: 1300000,
      country: "Russia",
      capital: "Cheboksary",
    },
    {
      id: 13,
      name: "Dagestan",
      population: 3000000,
      country: "Russia",
      capital: "Makhachkala",
    },
    {
      id: 14,
      name: "Irkutsk Oblast",
      population: 2400000,
      country: "Russia",
      capital: "Irkutsk",
    },
    {
      id: 15,
      name: "Ivanovo Oblast",
      population: 1000000,
      country: "Russia",
      capital: "Ivanovo",
    },
    {
      id: 16,
      name: "Kabardino-Balkaria",
      population: 800000,
      country: "Russia",
      capital: "Nalchik",
    },
    {
      id: 17,
      name: "Kaliningrad Oblast",
      population: 1000000,
      country: "Russia",
      capital: "Kaliningrad",
    },
    {
      id: 18,
      name: "Kaluga Oblast",
      population: 1000000,
      country: "Russia",
      capital: "Kaluga",
    },
    {
      id: 19,
      name: "Kamchatka Krai",
      population: 300000,
      country: "Russia",
      capital: "Petropavlovsk-Kamchatsky",
    },
    {
      id: 20,
      name: "Karachay-Cherkessia",
      population: 500000,
      country: "Russia",
      capital: "Cherkessk",
    },
    {
      id: 21,
      name: "Karelia",
      population: 600000,
      country: "Russia",
      capital: "Petrozavodsk",
    },
    {
      id: 22,
      name: "Kemerovo Oblast",
      population: 2700000,
      country: "Russia",
      capital: "Kemerovo",
    },
    {
      id: 23,
      name: "Khabarovsk Krai",
      population: 1600000,
      country: "Russia",
      capital: "Khabarovsk",
    },
    {
      id: 24,
      name: "Khakassia",
      population: 500000,
      country: "Russia",
      capital: "Abakan",
    },
    {
      id: 25,
      name: "Kirov Oblast",
      population: 1000000,
      country: "Russia",
      capital: "Kirov",
    },
    {
      id: 26,
      name: "Kostroma Oblast",
      population: 600000,
      country: "Russia",
      capital: "Kostroma",
    },
    {
      id: 27,
      name: "Krasnodar Krai",
      population: 5500000,
      country: "Russia",
      capital: "Krasnodar",
    },
    {
      id: 28,
      name: "Krasnoyarsk Krai",
      population: 2800000,
      country: "Russia",
      capital: "Krasnoyarsk",
    },
    {
      id: 29,
      name: "Kurgan Oblast",
      population: 800000,
      country: "Russia",
      capital: "Kurgan",
    },
    {
      id: 30,
      name: "Kursk Oblast",
      population: 1100000,
      country: "Russia",
      capital: "Kursk",
    },
    {
      id: 31,
      name: "Leningrad Oblast",
      population: 1800000,
      country: "Russia",
      capital: "Saint Petersburg",
    },
    {
      id: 32,
      name: "Lipetsk Oblast",
      population: 1200000,
      country: "Russia",
      capital: "Lipetsk",
    },
    {
      id: 33,
      name: "Magadan Oblast",
      population: 150000,
      country: "Russia",
      capital: "Magadan",
    },
    {
      id: 34,
      name: "Mari El",
      population: 700000,
      country: "Russia",
      capital: "Yoshkar-Ola",
    },
    {
      id: 35,
      name: "Mordovia",
      population: 800000,
      country: "Russia",
      capital: "Saransk",
    },
    {
      id: 36,
      name: "Moscow",
      population: 12000000,
      country: "Russia",
      capital: "Moscow",
    },
    {
      id: 37,
      name: "Moscow Oblast",
      population: 7000000,
      country: "Russia",
      capital: "Krasnogorsk",
    },
    {
      id: 38,
      name: "Murmansk Oblast",
      population: 800000,
      country: "Russia",
      capital: "Murmansk",
    },
    {
      id: 39,
      name: "Nizhny Novgorod Oblast",
      population: 3200000,
      country: "Russia",
      capital: "Nizhny Novgorod",
    },
    {
      id: 40,
      name: "North Ossetia-Alania",
      population: 700000,
      country: "Russia",
      capital: "Vladikavkaz",
    },
    {
      id: 41,
      name: "Novgorod Oblast",
      population: 600000,
      country: "Russia",
      capital: "Veliky Novgorod",
    },
    {
      id: 42,
      name: "Novosibirsk Oblast",
      population: 2800000,
      country: "Russia",
      capital: "Novosibirsk",
    },
    {
      id: 43,
      name: "Omsk Oblast",
      population: 1300000,
      country: "Russia",
      capital: "Omsk",
    },
    {
      id: 44,
      name: "Orenburg Oblast",
      population: 2000000,
      country: "Russia",
      capital: "Orenburg",
    },
    {
      id: 45,
      name: "Oryol Oblast",
      population: 800000,
      country: "Russia",
      capital: "Oryol",
    },
    {
      id: 46,
      name: "Penza Oblast",
      population: 1000000,
      country: "Russia",
      capital: "Penza",
    },
    {
      id: 47,
      name: "Perm Krai",
      population: 2600000,
      country: "Russia",
      capital: "Perm",
    },
    {
      id: 48,
      name: "Primorsky Krai",
      population: 2000000,
      country: "Russia",
      capital: "Vladivostok",
    },
    {
      id: 49,
      name: "Rostov Oblast",
      population: 4200000,
      country: "Russia",
      capital: "Rostov-on-Don",
    },
    {
      id: 50,
      name: "Ryazan Oblast",
      population: 1000000,
      country: "Russia",
      capital: "Ryazan",
    },
    {
      id: 51,
      name: "Saint Petersburg",
      population: 5400000,
      country: "Russia",
      capital: "Saint Petersburg",
    },
    {
      id: 52,
      name: "Sakha Republic",
      population: 900000,
      country: "Russia",
      capital: "Yakutsk",
    },
    {
      id: 53,
      name: "Sakhalin Oblast",
      population: 600000,
      country: "Russia",
      capital: "Yuzhno-Sakhalinsk",
    },
    {
      id: 54,
      name: "Samara Oblast",
      population: 3000000,
      country: "Russia",
      capital: "Samara",
    },
    {
      id: 55,
      name: "Saratov Oblast",
      population: 900000,
      country: "Russia",
      capital: "Saratov",
    },
    {
      id: 56,
      name: "Smolensk Oblast",
      population: 900000,
      country: "Russia",
      capital: "Smolensk",
    },
    {
      id: 57,
      name: "Stavropol Krai",
      population: 2700000,
      country: "Russia",
      capital: "Stavropol",
    },
    {
      id: 58,
      name: "Tambov Oblast",
      population: 1000000,
      country: "Russia",
      capital: "Tambov",
    },
    {
      id: 59,
      name: "Tatarstan",
      population: 3800000,
      country: "Russia",
      capital: "Kazan",
    },
    {
      id: 60,
      name: "Tomsk Oblast",
      population: 1000000,
      country: "Russia",
      capital: "Tomsk",
    },
    {
      id: 61,
      name: "Tula Oblast",
      population: 1200000,
      country: "Russia",
      capital: "Tula",
    },
    {
      id: 62,
      name: "Tyumen Oblast",
      population: 1300000,
      country: "Russia",
      capital: "Tyumen",
    },
    {
      id: 63,
      name: "Udmurt Republic",
      population: 1400000,
      country: "Russia",
      capital: "Izhevsk",
    },
    {
      id: 64,
      name: "Ulyanovsk Oblast",
      population: 1300000,
      country: "Russia",
      capital: "Ulyanovsk",
    },
    {
      id: 65,
      name: "Vladimir Oblast",
      population: 1300000,
      country: "Russia",
      capital: "Vladimir",
    },
    {
      id: 66,
      name: "Volgograd Oblast",
      population: 2500000,
      country: "Russia",
      capital: "Volgograd",
    },
    {
      id: 67,
      name: "Vologda Oblast",
      population: 1100000,
      country: "Russia",
      capital: "Vologda",
    },
    {
      id: 68,
      name: "Voronezh Oblast",
      population: 2200000,
      country: "Russia",
      capital: "Voronezh",
    },
    {
      id: 69,
      name: "Yamalo-Nenets Autonomous Okrug",
      population: 500000,
      country: "Russia",
      capital: "Salekhard",
    },
    {
      id: 70,
      name: "Yaroslavl Oblast",
      population: 1300000,
      country: "Russia",
      capital: "Yaroslavl",
    },
  ];